# Generated by Django 4.2.15 on 2025-02-23 01:25

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Категория расходов',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='money_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Вид денежных средств',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='move_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Вид движения',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_date', models.DateTimeField(default=datetime.datetime.now, verbose_name='Дата')),
                ('summa', models.FloatField(verbose_name='Сумма операции')),
                ('cashback', models.FloatField(blank=True, null=True, verbose_name='Кэшбек')),
                ('description', models.CharField(blank=True, max_length=256, null=True, verbose_name='Описание')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.category', verbose_name='Категория расходов')),
                ('moneytype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.money_type', verbose_name='Вид д/с')),
                ('movetype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.move_type', verbose_name='Вид движения')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Транзакция',
                'ordering': ['event_date', 'owner'],
            },
        ),
        migrations.CreateModel(
            name='current_total',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.DateTimeField(verbose_name='Период')),
                ('value', models.FloatField(blank=True, verbose_name='Сумма')),
                ('moneytype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.money_type', verbose_name='Вид д/с')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Текущий остаток',
                'ordering': ['-period', 'moneytype', 'owner'],
            },
        ),
    ]
